### ISSUE TITLE
Tawaran

### ISSUE THREAD

**Issue by rizrmd** [BosNaufal/micro-blogging-vue#1]
Mas Naufal

Saya Rizky dari PT. Andromedia (andromedia.co.id)
kemarin saya sudah kirim email ke   bosnaufalemail@gmail.com

kalau tertarik reply ya mas :)

**Comment by BosNaufal** [comment]
Halo Mas Rizky, maaf saya baru notice :grin: 
Udah saya balas~ Monggo dibaca :smiley:
